// import Footer from './Footer';
import Navbar from "../components/common/Navbar";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.css";

export const metadata = {
  title: "The-modelPT",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />

        {children}

        {/* <Footer /> */}
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script>
      <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
      </body>
    </html>
  );
}
